- Services:
    - homepage:
        icon: mdi-view-dashboard
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:3000
        description: Server dashboard
        server: my-docker
        container: homepage
    - atvloadly:
        icon: mdi-television-play
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:5533
        description: Apple TV IPA sideloader
        server: my-docker
        container: atvloadly
    - tailscale:
        icon: si-tailscale
        href: http://{{HOMEPAGE_VAR_TAILSCALE_IP}}:5252
        description: Zero-config VPN
        ping: http://localhost:8088
