title: Home Server
theme: dark
color: slate
headerStyle: clean
hideVersion: true

layout:
  Management:
    style: column
  Secondary Server (Pi):
    style: row
  Network:
    style: column
  Storage:
    style: column
  NAS:
    style: row
    columns: 2
