services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
