title: Game Server
theme: dark
color: slate
headerStyle: clean
hideVersion: true
fullWidth: true

layout:
  Games:
    style: row
    columns: 2
  Servers:
    style: row
    columns: 3
  Main server:
    style: row
    columns: 3
  Game server:
    style: row
    columns: 2
