services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    network_mode: host
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "${HOSTNAME}:3000,${HOSTNAME}.local:3000,localhost:3000"
    restart: unless-stopped
