services:
  tailscale-proxy:
    build: .
    container_name: tailscale-proxy
    network_mode: host
    env_file:
      - .env
      - path: ../../server-base/timezone.env
        required: true
    restart: unless-stopped
