#!/usr/bin/env python3
"""Render every server's Homepage config from server-base/fleet.json.

Per host it writes homepage/config/{services,settings}.yaml plus the shared
custom.css/custom.js. The Servers group (and Shared services on hosts other
than the one serving them) comes from fleet.json so every dashboard carries an
identical cross-link group; each host's own groups come verbatim from its
homepage/services.local.yaml and homepage/settings.local.yaml.

  python3 server-base/homepage/generate.py          # rewrite all hosts
  python3 server-base/homepage/generate.py --check  # exit 1 if any output is stale
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
HEADER = "# Generated by server-base/homepage/generate.py from server-base/fleet.json and\n# {local}. Edit those, then re-run the generator.\n"
LOCAL_GLANCES = "http://127.0.0.1:61208"


def scalar(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return json.dumps(value, ensure_ascii=False)


def emit(node, indent=0):
    pad = " " * indent
    lines = []
    if isinstance(node, dict):
        for key, value in node.items():
            if isinstance(value, (dict, list)) and value:
                lines.append(f"{pad}{key}:")
                lines += emit(value, indent + 2)
            else:
                lines.append(f"{pad}{key}: {scalar(value)}")
    else:
        for item in node:
            if isinstance(item, (dict, list)):
                sub = emit(item, indent + 2)
                lines.append(f"{pad}- {sub[0].lstrip()}")
                lines += sub[1:]
            else:
                lines.append(f"{pad}- {scalar(item)}")
    return lines


def spec_widgets(base, facts):
    """Six compact facts; inventory snapshot + native hourly usable RAM/software."""
    api = f"{base}/api/4"
    slow = 3600000

    def fixed(label, value):
        # Homepage native remapping avoids a second custom card renderer/poller.
        return {"field": "hostname", "label": label, "format": "text",
                "remap": [{"any": True, "to": value}]}

    return [
        {"type": "customapi", "url": f"{api}/system", "refreshInterval": slow, "display": "list",
         "mappings": [fixed("Platform", facts["platform"]), fixed("Board / SoC", facts["board"]),
                      fixed("CPU", facts["cpu"])]},
        {"type": "customapi", "url": f"{api}/mem", "refreshInterval": slow, "display": "list",
         "mappings": [{"field": "total", "label": "Memory", "format": "float",
                       "scale": "1/1073741824", "suffix": "GiB usable"}]},
        {"type": "customapi", "url": f"{api}/system", "refreshInterval": slow, "display": "list",
         "mappings": [fixed("Graphics", facts["graphics"]),
                      {"field": "linux_distro", "label": "Software", "format": "text",
                       "additionalField": {"field": "os_version", "format": "text", "prefix": "·"}}]},
    ]


def server_card(server, this_dir):
    local = server["dir"] == this_dir
    domain = f"{{{{HOMEPAGE_VAR_{server['domain_var']}}}}}"
    card = {"icon": server["icon"], "id": "server-" + server["key"]}
    if local:
        card["description"] = f"{server['description']} (this server)"
        card["widgets"] = spec_widgets(LOCAL_GLANCES, server["facts"])
    else:
        card["href"] = f"https://{domain}/"
        card["description"] = server["description"]
        card["siteMonitor"] = f"https://{domain}"
        if server.get("glances_url"):
            card["widgets"] = spec_widgets(server["glances_url"], server["facts"])
    return {server["name"]: card}


def shared_group(fleet):
    shared = fleet["shared_services"]
    cards = []
    for svc in shared["services"]:
        url = f"https://{{{{HOMEPAGE_VAR_{svc['domain_var']}}}}}"
        card = {"icon": svc["icon"], "href": f"{url}/", "description": svc["description"], "siteMonitor": url}
        if svc.get("widget"):
            card["widget"] = {**svc["widget"], "url": url}
        cards.append({svc["name"]: card})
    return {shared["group"]: cards}


def render_services(fleet, host_dir, local_text):
    groups = [{"Servers": [server_card(s, host_dir) for s in fleet["servers"]]}]
    shared_dir = next(s["dir"] for s in fleet["servers"] if s["key"] == fleet["shared_services"]["host"])
    out = "\n".join(emit(groups)) + "\n\n" + local_text.rstrip("\n") + "\n"
    if host_dir != shared_dir:
        out += "\n" + "\n".join(emit([shared_group(fleet)])) + "\n"
    return out


def render_settings(fleet, host_dir, local_text):
    host = fleet["hosts"][host_dir]
    base = {
        "title": host["title"],
        "theme": "dark",
        "color": "slate",
        "headerStyle": "boxed",
        "hideVersion": True,
        "fullWidth": True,
        "cardBlur": "sm",
        "useEqualHeights": True,
    }
    own = next(s for s in fleet["servers"] if s["dir"] == host_dir)
    extras = {"glances": own["glances_url"]}
    if host.get("topbar", {}).get("net"):
        extras["net"] = host["topbar"]["net"]
    if host.get("topbar", {}).get("rgb"):
        extras["rgb"] = host["topbar"]["rgb"]
    if host.get("topbar", {}).get("grouped"):
        extras.update({"grouped": True, "label": host["topbar"]["label"],
                       "disks": host["topbar"]["disks"]})
    if host.get("topbar", {}).get("grouped") and host["topbar"].get("gpuTypes"):
        extras["gpuTypes"] = host["topbar"]["gpuTypes"]
    base["topbarExtras"] = extras
    head = "\n".join(emit(base)) + "\n\nlayout:\n"
    servers = "  Servers:\n    style: row\n    columns: 3\n"
    shared_dir = next(s["dir"] for s in fleet["servers"] if s["key"] == fleet["shared_services"]["host"])
    tail = ""
    if host_dir != shared_dir:
        tail = f"  {fleet['shared_services']['group']}:\n    style: row\n    columns: 3\n"
    return head + servers + local_text.rstrip("\n") + "\n" + tail


def render_widgets(fleet, host_dir):
    """Top bar: this host's live stats only, from its own Glances."""
    top = fleet["hosts"][host_dir]["topbar"]
    widgets = [
        {"glances": {"url": LOCAL_GLANCES, "version": 4, "label": top["label"], "cpu": True, "mem": True,
                     "cputemp": True, "cpuSensorLabel": "CPU", "uptime": True, "disk": top["disks"],
                     "expanded": True}},
        {"datetime": {"text_size": "xl", "format": {"timeStyle": "short", "dateStyle": "short", "hourCycle": "h23"}}},
    ]
    return "\n".join(emit(widgets)) + "\n"


def render_js(fleet, host_dir):
    accents = json.dumps(fleet["hosts"][host_dir]["accents"], sort_keys=True)
    template = (HERE / "custom.js.in").read_text().replace("@ACCENTS@", accents)
    if fleet["hosts"][host_dir]["topbar"].get("grouped"):
        # Replace the legacy extras poller, not add a second scheduler. Keep
        # other hosts' generated scripts byte-identical and React untouched.
        marker = "// Top bar extras the Glances info widget cannot show:"
        if marker not in template:
            raise ValueError("custom.js.in is missing its extras boundary")
        template = template.split(marker, 1)[0] + (HERE / "grouped-topbar.js").read_text()
    return template


def render_css(fleet, host_dir):
    css = (HERE / "custom.css").read_text()
    if fleet["hosts"][host_dir]["topbar"].get("grouped"):
        css += "\n" + (HERE / "grouped-topbar.css").read_text()
    return css


def outputs(fleet):
    for host_dir in fleet["hosts"]:
        hp = REPO / host_dir / "homepage"
        cfg = hp / "config"
        header = HEADER.format(local=f"{host_dir}/homepage/services.local.yaml")
        yield cfg / "services.yaml", header + render_services(fleet, host_dir, (hp / "services.local.yaml").read_text())
        header = HEADER.format(local=f"{host_dir}/homepage/settings.local.yaml")
        yield cfg / "settings.yaml", header + render_settings(fleet, host_dir, (hp / "settings.local.yaml").read_text())
        yield cfg / "widgets.yaml", HEADER.format(local="this host's topbar entry") + render_widgets(fleet, host_dir)
        yield cfg / "custom.css", "/* Generated copy of server-base/homepage/custom.css. */\n" + render_css(fleet, host_dir)
        yield cfg / "custom.js", "// Generated from server-base/homepage/custom.js.in.\n" + render_js(fleet, host_dir)


def main(argv):
    check = argv[1:] == ["--check"]
    if argv[1:] not in ([], ["--check"]):
        print("usage: generate.py [--check]", file=sys.stderr)
        return 2
    fleet = json.loads((REPO / "server-base/fleet.json").read_text())
    stale = []
    for path, content in outputs(fleet):
        if path.exists() and path.read_text() == content:
            continue
        if check:
            stale.append(str(path.relative_to(REPO)))
        else:
            path.write_text(content)
            print(f"wrote {path.relative_to(REPO)}")
    if stale:
        print("stale (run server-base/homepage/generate.py):\n  " + "\n  ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
