#!/usr/bin/env python3
"""Render every server's Homepage config from server-base/fleet.json.

Per host it writes homepage/config/{services,settings}.yaml plus the shared
custom.css/custom.js. The Servers group (and Shared services on hosts other
than the one serving them) comes from fleet.json so every dashboard carries an
identical cross-link group; each host's own groups come verbatim from its
homepage/services.local.yaml and homepage/settings.local.yaml.

  python3 server-base/homepage/generate.py          # rewrite all hosts
  python3 server-base/homepage/generate.py --check  # exit 1 if any output is stale
"""
import json
import sys
from html import escape
from math import ceil
from urllib.parse import quote
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
HEADER = "# Generated by server-base/homepage/generate.py from server-base/fleet.json and\n# {local}. Edit those, then re-run the generator.\n"
LOCAL_GLANCES = "http://127.0.0.1:61208"


def scalar(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return json.dumps(value, ensure_ascii=False)


def emit(node, indent=0):
    pad = " " * indent
    lines = []
    if isinstance(node, dict):
        for key, value in node.items():
            if isinstance(value, (dict, list)) and value:
                lines.append(f"{pad}{key}:")
                lines += emit(value, indent + 2)
            else:
                lines.append(f"{pad}{key}: {scalar(value)}")
    else:
        for item in node:
            if isinstance(item, (dict, list)):
                sub = emit(item, indent + 2)
                lines.append(f"{pad}- {sub[0].lstrip()}")
                lines += sub[1:]
            else:
                lines.append(f"{pad}- {scalar(item)}")
    return lines


def spec_widgets(base, facts):
    """Six compact facts; inventory snapshot + native hourly usable RAM/software."""
    api = f"{base}/api/4"
    slow = 3600000

    def fixed(label, value):
        # Homepage native remapping avoids a second custom card renderer/poller.
        return {"field": "hostname", "label": label, "format": "text",
                "remap": [{"any": True, "to": value}]}

    return [
        {"type": "customapi", "url": f"{api}/system", "refreshInterval": slow, "display": "list",
         "mappings": [fixed("Platform", facts["platform"]), fixed("Board / SoC", facts["board"]),
                      fixed("CPU", facts["cpu"])]},
        {"type": "customapi", "url": f"{api}/mem", "refreshInterval": slow, "display": "list",
         "mappings": [{"field": "total", "label": "Memory", "format": "float",
                       "scale": "1/1073741824", "suffix": "GiB usable"}]},
        {"type": "customapi", "url": f"{api}/system", "refreshInterval": slow, "display": "list",
         "mappings": [fixed("Graphics", facts["graphics"]),
                      {"field": "linux_distro", "label": "Software", "format": "text",
                       "additionalField": {"field": "os_version", "format": "text", "prefix": "·"}}]},
    ]


def server_card(server, this_dir):
    local = server["dir"] == this_dir
    domain = f"{{{{HOMEPAGE_VAR_{server['domain_var']}}}}}"
    card = {"icon": server["icon"], "id": "server-" + server["key"]}
    if local:
        card["description"] = f"{server['description']} (this server)"
        card["widgets"] = spec_widgets(LOCAL_GLANCES, server["facts"])
    else:
        card["href"] = f"https://{domain}/"
        card["description"] = server["description"]
        card["siteMonitor"] = f"https://{domain}"
        if server.get("glances_url"):
            card["widgets"] = spec_widgets(server["glances_url"], server["facts"])
    return {server["name"]: card}


def shared_group(fleet):
    shared = fleet["shared_services"]
    cards = []
    for svc in shared["services"]:
        url = f"https://{{{{HOMEPAGE_VAR_{svc['domain_var']}}}}}"
        card = {"icon": svc["icon"], "href": f"{url}/", "description": svc["description"], "siteMonitor": url}
        if svc.get("widget"):
            card["widget"] = {**svc["widget"], "url": url}
        cards.append({svc["name"]: card})
    return {shared["group"]: cards}


def render_services(fleet, host_dir, local_text):
    groups = [{"Servers": [server_card(s, host_dir) for s in fleet["servers"]]}]
    shared_dir = next(s["dir"] for s in fleet["servers"] if s["key"] == fleet["shared_services"]["host"])
    out = "\n".join(emit(groups)) + "\n\n" + local_text.rstrip("\n") + "\n"
    if host_dir != shared_dir:
        out += "\n" + "\n".join(emit([shared_group(fleet)])) + "\n"
    return out


def render_settings(fleet, host_dir, local_text):
    host = fleet["hosts"][host_dir]
    base = {
        "title": host["title"],
        "theme": "dark",
        "color": "slate",
        "headerStyle": "boxed",
        "hideVersion": True,
        "fullWidth": True,
        "cardBlur": "sm",
        "useEqualHeights": True,
    }
    own = next(s for s in fleet["servers"] if s["dir"] == host_dir)
    extras = {"glances": own["glances_url"]}
    if host.get("topbar", {}).get("net"):
        extras["net"] = host["topbar"]["net"]
    if "rgb" in host.get("topbar", {}):
        raise ValueError("topbar.rgb is not supported: RGB lighting belongs on the OpenRGB card, not the top bar")
    if host.get("topbar", {}).get("grouped"):
        extras.update({"grouped": True, "label": host["topbar"]["label"],
                       "disks": host["topbar"]["disks"]})
    if host.get("topbar", {}).get("grouped"):
        top = host["topbar"]
        extras.update({"safeSSDHealth": top.get("safeSSDHealth", False),
                       "filesystemIntervalMs": max(300000, top.get("filesystemIntervalMs", 300000)),
                       "smartIntervalMs": max(600000, top.get("smartIntervalMs", 600000))})
        for key in ["gpuTypes", "gpuFields", "gpu", "wifi", "diskLabels", "temperatureLabels", "hddDisks", "hddActivityStats"]:
            if key in top:
                extras[key] = top[key]
    base["topbarExtras"] = extras
    head = "\n".join(emit(base)) + "\n\nlayout:\n"
    servers = "  Servers:\n    style: row\n    columns: 3\n"
    shared_dir = next(s["dir"] for s in fleet["servers"] if s["key"] == fleet["shared_services"]["host"])
    tail = ""
    if host_dir != shared_dir:
        tail = f"  {fleet['shared_services']['group']}:\n    style: row\n    columns: 3\n"
    return head + servers + local_text.rstrip("\n") + "\n" + tail


def render_widgets(fleet, host_dir):
    """Top bar: this host's live stats only, from its own Glances."""
    top = fleet["hosts"][host_dir]["topbar"]
    widgets = [
        {"glances": {"url": LOCAL_GLANCES, "version": 4, "label": top["label"], "cpu": True, "mem": True,
                     "cputemp": True, "cpuSensorLabel": "CPU", "uptime": True, "disk": top["disks"],
                     "expanded": True}},
        {"datetime": {"text_size": "xl", "format": {"timeStyle": "short", "dateStyle": "short", "hourCycle": "h23"}}},
    ]
    return "\n".join(emit(widgets)) + "\n"


def render_js(fleet, host_dir):
    accents = json.dumps(fleet["hosts"][host_dir]["accents"], sort_keys=True)
    template = (HERE / "custom.js.in").read_text().replace("@ACCENTS@", accents)
    if fleet["hosts"][host_dir]["topbar"].get("grouped"):
        # Replace the legacy extras poller, not add a second scheduler. Keep
        # other hosts' generated scripts byte-identical and React untouched.
        marker = "// Top bar extras the Glances info widget cannot show:"
        if marker not in template:
            raise ValueError("custom.js.in is missing its extras boundary")
        template = template.split(marker, 1)[0] + (HERE / "grouped-topbar.js").read_text()
    return template


def loading_css(top):
    """CSS-first, no-HTTP shell that has the same geometry as the live panel.

    Homepage loads custom.js after hydration. Hide its known native slot only
    when scripting is enabled, and reserve the grouped footprint in CSS (an SVG
    data URI whose text is decorative; a pseudo-element carries the accessible
    "loading" text). If the enhancement script never arrives, fail open to the
    native widget after 12 seconds. Tile heights come from each host's row
    counts, so the shell and live tiles share one set of custom properties.
    """
    health = top.get("safeSSDHealth", False) is True
    state = "Loading"
    compute = [("CPU", ["Usage", "Load · 15m", "Temp", "Warn"], state), ("RAM", ["Used", "Free", "Total"], state)]
    gpus = [(kind, top.get("gpuFields", {}).get(device,
                                              ["Usage", "Temp", "VRAM" if kind == "dGPU" else "Memory", "Memory used", "Fan"]), state)
            for device, kind in top.get("gpuTypes", {}).items()]
    storage = []
    for label in top.get("temperatureLabels", []):
        rows = ["Temp", "Warn"] + (["Health", "Wear"] if health and label == "NVMe" else [])
        storage.append((label if label == "NVMe" else f"{label} temperature", rows, state))
    if health and "NVMe" not in top.get("temperatureLabels", []):
        storage.append(("NVMe health", ["Health", "Wear"], state))
    hdd = set(top.get("hddDisks", []))
    storage += [(top.get("diskLabels", {}).get(mount, "System disk" if mount == "/etc/hostname" else mount),
                 ["Used", "Free", "Total"], "Not monitored · HDD" if mount in hdd and not top.get("hddActivityStats") else state) for mount in top["disks"]]
    connectivity = [(top["net"], ["Upload", "Download"], state)] if top.get("net") else []
    if top.get("wifi"):
        connectivity.append(("Wi-Fi", ["Signal", "Link"], state))
    system = [("Host", ["Uptime", "Clock"], state)]
    groups = [("Compute", compute + gpus), ("Storage", storage), ("Connectivity", connectivity), ("System", system)]

    # Fixed row heights (px): h3 22 + detail 18 (GPU 32) + 18 per row + meter 8 + state
    # (4 + 14; storage 4 + 28, because its age text can wrap to two lines).
    def tallest(tiles):
        return max((len(rows) for _, rows, _ in tiles), default=0)
    heights = {"compute": 66 + 18 * tallest(compute), "storage": 80 + 18 * tallest(storage),
               "net": 66 + 18 * tallest(connectivity), "system": 66 + 18 * tallest(system)}
    if gpus:
        heights["gpu"] = 80 + 18 * tallest(gpus)
    tile_h = [[heights["compute"] if i < 2 else heights["gpu"] for i in range(len(compute + gpus))],
              [heights["storage"]] * len(storage), [heights["net"]] * len(connectivity), [heights["system"]] * len(system)]

    def group_height(hs, cols):
        rows = [hs[i:i + cols] for i in range(0, len(hs), cols)]
        return 46 + sum(max(r) for r in rows) + 10 * (len(rows) - 1) if rows else 46

    storage_cols = 3 if len(storage) > 4 else 2
    body = '<div class="monitor-groups">'
    for title, tiles in groups:
        body += f'<section class="monitor-group"><h2>{escape(title)}</h2><div class="monitor-tiles">'
        for label, rows, tile_state in tiles:
            body += f'<article class="monitor-tile"><h3>{escape(label)}</h3><p class="monitor-detail"></p><dl>'
            body += ''.join(f'<div><dt>{escape(row)}</dt><dd>—</dd></div>' for row in rows)
            body += f'</dl><div class="monitor-meter"></div><p class="monitor-state">{escape(tile_state)}</p></article>'
        body += '</div></section>'
    body += '</div>'
    vars_ = "".join(f" --monitor-h-{key}: {value}px;" for key, value in heights.items())
    vars_ += f" --monitor-storage-cols: {storage_cols}; --monitor-storage-fr: {'1.8fr' if storage_cols == 3 else '1.2fr'};"
    css = f"#information-widgets {{{vars_} }}\n"
    for width, columns, media, header, notice in [
            (1368, [3, storage_cols, 1, 1], "", 44, 30),
            (768, [3, 2, 2, 2], "@media (max-width:1050px)", 44, 30),
            (350, [2, 2, 2, 2], "@media (max-width:600px)", 76, 44)]:
        sizes = [group_height(hs, cols) for hs, cols in zip(tile_h, columns)]
        height = header + notice + (max(sizes) if width > 1050 else max(sizes[:2]) + max(sizes[2:]) if width > 600 else sum(sizes))
        # Grid borders occupy 1px on subsequent mobile/tablet rows.
        height += 0 if width > 1050 else 1 if width > 600 else 3
        style = (HERE / "grouped-topbar.css").read_text()
        style += f' *{{box-sizing:border-box}} .host-monitor{{font-family:Arial,sans-serif;{vars_.replace(" --", "--")}}}'
        # Media queries inside an SVG use its own viewport.
        html = (f'<div xmlns="http://www.w3.org/1999/xhtml" class="host-monitor"><style>{escape(style)}</style>'
                f'<header class="monitor-header"><span class="monitor-host">{escape(top["label"])}</span>'
                '<span class="monitor-cadence">Waiting for metrics</span></header>'
                '<p class="monitor-notice"></p>' + body + '</div>')
        svg = f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}"><foreignObject width="100%" height="100%">{html}</foreignObject></svg>'
        rule = f'''#information-widgets:not(.host-monitor-ready)::before {{
  content: "Host metrics loading…"; display: block; box-sizing: border-box;
  height: {height}px; padding: {header + 16}px 14px 0; color: #fde68a;
  font-size: 11px; line-height: 14px;
  background: url("data:image/svg+xml,{quote(svg, safe='')}") 0 0 / 100% 100% no-repeat;
  animation: monitor-shell-fallback 0s 12s forwards;
}}'''
        css += f"@media (scripting:enabled) {{ {media + ' {' if media else ''}\n{rule}\n{'}' if media else ''} }}\n"
    css += '''@media (scripting:enabled) {
  #information-widgets:not(.host-monitor-ready) { display:block; padding:0; border:0; }
  #information-widgets:not(.host-monitor-ready) #widgets-wrap,
  #information-widgets:not(.host-monitor-ready) .information-widget-datetime {
    visibility:hidden; position:absolute; animation:monitor-native-fallback 0s 12s forwards;
  }
}
@keyframes monitor-shell-fallback { to { display:none; } }
@keyframes monitor-native-fallback { to { visibility:visible; position:static; } }
'''
    return css


def render_css(fleet, host_dir):
    css = (HERE / "custom.css").read_text()
    if fleet["hosts"][host_dir]["topbar"].get("grouped"):
        css += "\n" + (HERE / "grouped-topbar.css").read_text()
        css += "\n" + loading_css(fleet["hosts"][host_dir]["topbar"])
    return css


def outputs(fleet):
    for host_dir in fleet["hosts"]:
        hp = REPO / host_dir / "homepage"
        cfg = hp / "config"
        header = HEADER.format(local=f"{host_dir}/homepage/services.local.yaml")
        yield cfg / "services.yaml", header + render_services(fleet, host_dir, (hp / "services.local.yaml").read_text())
        header = HEADER.format(local=f"{host_dir}/homepage/settings.local.yaml")
        yield cfg / "settings.yaml", header + render_settings(fleet, host_dir, (hp / "settings.local.yaml").read_text())
        yield cfg / "widgets.yaml", HEADER.format(local="this host's topbar entry") + render_widgets(fleet, host_dir)
        yield cfg / "custom.css", "/* Generated copy of server-base/homepage/custom.css. */\n" + render_css(fleet, host_dir)
        yield cfg / "custom.js", "// Generated from server-base/homepage/custom.js.in.\n" + render_js(fleet, host_dir)


def main(argv):
    check = argv[1:] == ["--check"]
    if argv[1:] not in ([], ["--check"]):
        print("usage: generate.py [--check]", file=sys.stderr)
        return 2
    fleet = json.loads((REPO / "server-base/fleet.json").read_text())
    stale = []
    for path, content in outputs(fleet):
        if path.exists() and path.read_text() == content:
            continue
        if check:
            stale.append(str(path.relative_to(REPO)))
        else:
            path.write_text(content)
            print(f"wrote {path.relative_to(REPO)}")
    if stale:
        print("stale (run server-base/homepage/generate.py):\n  " + "\n  ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
